name: space_x_now
description: SpaceX Now
version: 1.0.0
publish_to: 'none'

sdkPath: .fvm/flutter_sdk

environment:
  sdk: ^3.6.1

workspace:
  - apps/space_x_now_app
  - packages/core
  - packages/ui_components
  - packages/launches
  - packages/rockets

dev_dependencies:
  melos: ^7.1.0

melos:
  scripts:
    analyze:
      exec: dart analyze
    format:
      run: dart format .
    build_app:
      run: melos exec -c 1 --order-dependents --fail-fast --scope=space_x_now_app --depends-on="auto_route_generator" -- \
          dart run build_runner build --delete-conflicting-outputs
    build_core_package:
      run: melos exec -c 1 --order-dependents --fail-fast --scope=space_x_now_core --depends-on="build_runner" -- \
          dart run build_runner build --delete-conflicting-outputs
    build_launches_package:
      run: melos exec -c 1 --order-dependents --fail-fast --scope=space_x_now_launches --depends-on="build_runner" -- \
          dart run build_runner build --delete-conflicting-outputs
    build_rockets_package:
      run: melos exec -c 1 --order-dependents --fail-fast --scope=space_x_now_rockets --depends-on="build_runner" -- \
          dart run build_runner build --delete-conflicting-outputs
