name: space_x_now
description: SpaceX Now
version: 1.0.0
publish_to: 'none'

sdkPath: .fvm/flutter_sdk

environment:
  sdk: ^3.6.1

workspace:
  - apps/space_x_now_app
  - packages/core
  - packages/ui_components
  - packages/launches
  - packages/rockets
  - packages/launchpad
  - packages/payload
  - packages/di

dev_dependencies:
  melos: ^7.1.0

melos:  
  scripts:
    analyze:
      exec: dart analyze
    format:
      run: dart format .
    build_app:clean:
      run: melos exec --scope=space_x_now_app -- "dart run build_runner clean && dart run build_runner build --delete-conflicting-outputs"
    build_app:
      run: melos exec --scope=space_x_now_app -- "dart run build_runner build --delete-conflicting-outputs"
    build_core_package:clean:
      run: melos exec --scope=space_x_now_core -- "dart run build_runner clean && dart run build_runner build --delete-conflicting-outputs"
    build_core_package:
      run: melos exec --scope=space_x_now_core -- "dart run build_runner build --delete-conflicting-outputs"
    build_launches_package:clean:
      run: melos exec --scope=space_x_launches -- "dart run build_runner clean && dart run build_runner build --delete-conflicting-outputs"
    build_launches_package:
      run: melos exec --scope=space_x_launches -- "dart run build_runner build --delete-conflicting-outputs"
    build_rockets_package:clean:
      run: melos exec --scope=space_x_rockets -- "dart run build_runner clean && dart run build_runner build --delete-conflicting-outputs"
    build_rockets_package:
      run: melos exec --scope=space_x_rockets -- "dart run build_runner build --delete-conflicting-outputs"
    build_launchpad_package:clean:
      run: melos exec --scope=space_x_launchpad -- "dart run build_runner clean && dart run build_runner build --delete-conflicting-outputs"
    build_launchpad_package:
      run: melos exec --scope=space_x_launchpad -- "dart run build_runner build --delete-conflicting-outputs"
    build_payload_package:clean:
      run: melos exec --scope=space_x_payload -- "dart run build_runner clean && dart run build_runner build --delete-conflicting-outputs"
    build_payload_package:
      run: melos exec --scope=space_x_payload -- "dart run build_runner build --delete-conflicting-outputs"