name: space_x_launches
description: Feature of Launches for SpaceX Now app
version: 1.0.0
publish_to: 'none'

environment:
  sdk: ^3.6.1
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  
  # Core
  space_x_now_core:
    path: ../core

  # Shared UI components
  space_x_now_ui_components:
    path: ../ui_components

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

resolution: workspace