name: space_x_now_ui_components
description: Shared UI components, themes, and widgets for SpaceX Now
version: 1.0.0
publish_to: 'none'

environment:
  sdk: ">=3.6.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  # Fonts
  google_fonts: ^6.3.1

  # Image caching & placeholders
  cached_network_image: ^3.4.1
  flutter_svg: ^2.2.1

  # UI & Icons
  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.10.0

  # Loading & Shimmer effects
  shimmer: ^3.0.0

  # Layout & Spacing
  gap: ^3.0.1

  # Toast & Notifications
  toastification: ^3.0.3
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/logo/

resolution: workspace
