name: space_x_now_di
description: Dependency Injection for SpaceX Now
version: 1.0.0
publish_to: 'none'

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  # Dependency injection
  get_it: ^8.2.0
  injectable: ^2.5.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  injectable_generator: ^2.8.1


flutter:
  uses-material-design: true

resolution: workspace
